import { Component, signal, inject, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Pagination } from '../../../shared/components/pagination/pagination';
import { PaginationService } from '../../../core/services/pagination';
import { RouterLink } from '@angular/router';

interface Pago {
  idRecibo: string;
  fecha: string;
  concepto: string;
  puesto: string;
  socio: string;
  avatar: string;
  monto: number;
  estado: 'Completado' | 'Pendiente' | 'Vencido';
}

@Component({
  selector: 'app-pagos-cajero',
  imports: [CommonModule, Pagination, RouterLink],
  templateUrl: './pagos-cajero.html',
  styleUrl: './pagos-cajero.css',
})
export class PagosCajero {
  private paginationService = inject(PaginationService);

  allPagos = signal<Pago[]>([
    {
      idRecibo: '#REC-92834',
      fecha: '14 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'B-102',
      socio: 'Julianna De Marco',
      avatar: 'JD',
      monto: 3500.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92835',
      fecha: '15 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'A-045',
      socio: 'Alex Rivera',
      avatar: 'AR',
      monto: 150.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92836',
      fecha: '01 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'A-001',
      socio: 'Carlos Mendoza',
      avatar: 'CM',
      monto: 3200.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92837',
      fecha: '01 Abr, 2026',
      concepto: 'Cuota de Mantenimiento',
      puesto: 'A-002',
      socio: 'Lucía Fernández',
      avatar: 'LF',
      monto: 180.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92838',
      fecha: '01 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'A-003',
      socio: 'Diego Ramírez',
      avatar: 'DR',
      monto: 2950.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92839',
      fecha: '01 Abr, 2026',
      concepto: 'Luz',
      puesto: 'A-004',
      socio: 'Mariana Soto',
      avatar: 'MS',
      monto: 230.5,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92840',
      fecha: '02 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'A-005',
      socio: 'José Martínez',
      avatar: 'JM',
      monto: 3100.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92841',
      fecha: '02 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'A-006',
      socio: 'Ana López',
      avatar: 'AL',
      monto: 160.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92842',
      fecha: '02 Abr, 2026',
      concepto: 'Agua',
      puesto: 'A-007',
      socio: 'Pedro García',
      avatar: 'PG',
      monto: 95.75,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92843',
      fecha: '02 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'A-008',
      socio: 'Isabella Ruiz',
      avatar: 'IR',
      monto: 3450.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92844',
      fecha: '03 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'A-009',
      socio: 'Fernando Torres',
      avatar: 'FT',
      monto: 3050.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92845',
      fecha: '03 Abr, 2026',
      concepto: 'Cuota Extraordinaria',
      puesto: 'A-010',
      socio: 'Laura Chávez',
      avatar: 'LC',
      monto: 450.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92846',
      fecha: '03 Abr, 2026',
      concepto: 'Estacionamiento',
      puesto: 'E-001',
      socio: 'Miguel Ángel',
      avatar: 'MA',
      monto: 80.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92847',
      fecha: '03 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'B-001',
      socio: 'Sofía Herrera',
      avatar: 'SH',
      monto: 3600.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92848',
      fecha: '04 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'B-002',
      socio: 'Andrés Gómez',
      avatar: 'AG',
      monto: 175.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92849',
      fecha: '04 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'B-003',
      socio: 'Paula Ríos',
      avatar: 'PR',
      monto: 3400.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92850',
      fecha: '04 Abr, 2026',
      concepto: 'Luz',
      puesto: 'B-004',
      socio: 'Héctor Salas',
      avatar: 'HS',
      monto: 210.3,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92851',
      fecha: '05 Abr, 2026',
      concepto: 'Agua',
      puesto: 'B-005',
      socio: 'Daniela Ponce',
      avatar: 'DP',
      monto: 88.9,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92852',
      fecha: '05 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'B-006',
      socio: 'Raúl Estrada',
      avatar: 'RE',
      monto: 3300.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92853',
      fecha: '05 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'B-007',
      socio: 'Patricia Núñez',
      avatar: 'PN',
      monto: 190.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92854',
      fecha: '05 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'B-008',
      socio: 'Jorge Silva',
      avatar: 'JS',
      monto: 3150.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92855',
      fecha: '06 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'B-009',
      socio: 'Valeria Cruz',
      avatar: 'VC',
      monto: 3550.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92856',
      fecha: '06 Abr, 2026',
      concepto: 'Cuota de Mantenimiento',
      puesto: 'B-010',
      socio: 'Luis Pérez',
      avatar: 'LP',
      monto: 185.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92857',
      fecha: '06 Abr, 2026',
      concepto: 'Estacionamiento',
      puesto: 'E-002',
      socio: 'Claudia Vega',
      avatar: 'CV',
      monto: 85.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92858',
      fecha: '06 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'C-001',
      socio: 'Ricardo Navarro',
      avatar: 'RN',
      monto: 3700.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92859',
      fecha: '07 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'C-002',
      socio: 'Elena Blanco',
      avatar: 'EB',
      monto: 3650.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92860',
      fecha: '07 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'C-003',
      socio: 'Tomás Aguilar',
      avatar: 'TA',
      monto: 170.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92861',
      fecha: '07 Abr, 2026',
      concepto: 'Luz',
      puesto: 'C-004',
      socio: 'Gabriela Castro',
      avatar: 'GC',
      monto: 205.2,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92862',
      fecha: '07 Abr, 2026',
      concepto: 'Agua',
      puesto: 'C-005',
      socio: 'Javier Ortiz',
      avatar: 'JO',
      monto: 92.15,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92863',
      fecha: '08 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'C-006',
      socio: 'Natalia Prieto',
      avatar: 'NP',
      monto: 3450.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92864',
      fecha: '08 Abr, 2026',
      concepto: 'Cuota Extraordinaria',
      puesto: 'C-007',
      socio: 'Sergio León',
      avatar: 'SL',
      monto: 500.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92865',
      fecha: '08 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'C-008',
      socio: 'Carolina Rivas',
      avatar: 'CR',
      monto: 3250.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92866',
      fecha: '08 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'C-009',
      socio: 'Hernán Díaz',
      avatar: 'HD',
      monto: 165.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92867',
      fecha: '09 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'C-010',
      socio: 'Irene Salgado',
      avatar: 'IS',
      monto: 3550.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92868',
      fecha: '09 Abr, 2026',
      concepto: 'Luz',
      puesto: 'D-001',
      socio: 'Pablo Cárdenas',
      avatar: 'PC',
      monto: 215.8,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92869',
      fecha: '09 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'D-002',
      socio: 'Mónica Reyes',
      avatar: 'MR',
      monto: 3400.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92870',
      fecha: '09 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'D-003',
      socio: 'Oscar Valle',
      avatar: 'OV',
      monto: 190.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92871',
      fecha: '10 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'D-004',
      socio: 'Andrea Molina',
      avatar: 'AM',
      monto: 3600.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92872',
      fecha: '10 Abr, 2026',
      concepto: 'Agua',
      puesto: 'D-005',
      socio: 'Felipe Ramos',
      avatar: 'FR',
      monto: 90.4,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92873',
      fecha: '10 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'D-006',
      socio: 'Camila Duarte',
      avatar: 'CD',
      monto: 3300.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92874',
      fecha: '10 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'D-007',
      socio: 'Alberto Lara',
      avatar: 'AL',
      monto: 175.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92875',
      fecha: '11 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'D-008',
      socio: 'Beatriz Quintero',
      avatar: 'BQ',
      monto: 3450.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92876',
      fecha: '11 Abr, 2026',
      concepto: 'Luz',
      puesto: 'D-009',
      socio: 'Gustavo Paredes',
      avatar: 'GP',
      monto: 220.6,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92877',
      fecha: '11 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'D-010',
      socio: 'Verónica Salas',
      avatar: 'VS',
      monto: 3350.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92878',
      fecha: '11 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'E-003',
      socio: 'Hugo Lozano',
      avatar: 'HL',
      monto: 180.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92879',
      fecha: '12 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'E-004',
      socio: 'Rebeca Ortiz',
      avatar: 'RO',
      monto: 3100.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92880',
      fecha: '12 Abr, 2026',
      concepto: 'Cuota de Mantenimiento',
      puesto: 'E-005',
      socio: 'Ignacio Flores',
      avatar: 'IF',
      monto: 195.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92881',
      fecha: '12 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'E-006',
      socio: 'Tamara Ruiz',
      avatar: 'TR',
      monto: 3250.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92882',
      fecha: '12 Abr, 2026',
      concepto: 'Agua',
      puesto: 'E-007',
      socio: 'Marcos Herrera',
      avatar: 'MH',
      monto: 93.2,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92883',
      fecha: '13 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'E-008',
      socio: 'Silvia Fuentes',
      avatar: 'SF',
      monto: 3500.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92884',
      fecha: '13 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'E-009',
      socio: 'Mauricio Vega',
      avatar: 'MV',
      monto: 185.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92885',
      fecha: '13 Abr, 2026',
      concepto: 'Luz',
      puesto: 'E-010',
      socio: 'Julia Campos',
      avatar: 'JC',
      monto: 218.9,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92886',
      fecha: '13 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'F-001',
      socio: 'Rodrigo Peña',
      avatar: 'RP',
      monto: 3400.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92887',
      fecha: '14 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'F-002',
      socio: 'Karen López',
      avatar: 'KL',
      monto: 3350.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92888',
      fecha: '14 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'F-003',
      socio: 'Adrián Roldán',
      avatar: 'AR',
      monto: 190.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92889',
      fecha: '14 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'F-004',
      socio: 'Pilar Cabrera',
      avatar: 'PC',
      monto: 3200.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92890',
      fecha: '14 Abr, 2026',
      concepto: 'Agua',
      puesto: 'F-005',
      socio: 'Esteban Arias',
      avatar: 'EA',
      monto: 91.6,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92891',
      fecha: '15 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'F-006',
      socio: 'Lorena Ibáñez',
      avatar: 'LI',
      monto: 3450.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92892',
      fecha: '15 Abr, 2026',
      concepto: 'Luz',
      puesto: 'F-007',
      socio: 'Santiago Bravo',
      avatar: 'SB',
      monto: 222.4,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92893',
      fecha: '15 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'F-008',
      socio: 'Teresa Méndez',
      avatar: 'TM',
      monto: 3300.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92894',
      fecha: '15 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'F-009',
      socio: 'César Padilla',
      avatar: 'CP',
      monto: 180.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92895',
      fecha: '16 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'F-010',
      socio: 'Rosa Delgado',
      avatar: 'RD',
      monto: 3500.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92896',
      fecha: '14 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'B-102',
      socio: 'Julianna De Marco',
      avatar: 'JD',
      monto: 3500.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92897',
      fecha: '15 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'A-045',
      socio: 'Alex Rivera',
      avatar: 'AR',
      monto: 150.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92898',
      fecha: '01 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'A-001',
      socio: 'Carlos Mendoza',
      avatar: 'CM',
      monto: 3200.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-92899',
      fecha: '01 Abr, 2026',
      concepto: 'Cuota de Mantenimiento',
      puesto: 'A-002',
      socio: 'Lucía Fernández',
      avatar: 'LF',
      monto: 180.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928100',
      fecha: '01 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'A-003',
      socio: 'Diego Ramírez',
      avatar: 'DR',
      monto: 2950.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928101',
      fecha: '01 Abr, 2026',
      concepto: 'Luz',
      puesto: 'A-004',
      socio: 'Mariana Soto',
      avatar: 'MS',
      monto: 230.5,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928102',
      fecha: '02 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'A-005',
      socio: 'José Martínez',
      avatar: 'JM',
      monto: 3100.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928103',
      fecha: '02 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'A-006',
      socio: 'Ana López',
      avatar: 'AL',
      monto: 160.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928104',
      fecha: '02 Abr, 2026',
      concepto: 'Agua',
      puesto: 'A-007',
      socio: 'Pedro García',
      avatar: 'PG',
      monto: 95.75,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928105',
      fecha: '02 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'A-008',
      socio: 'Isabella Ruiz',
      avatar: 'IR',
      monto: 3450.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928106',
      fecha: '03 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'A-009',
      socio: 'Fernando Torres',
      avatar: 'FT',
      monto: 3050.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928107',
      fecha: '03 Abr, 2026',
      concepto: 'Cuota Extraordinaria',
      puesto: 'A-010',
      socio: 'Laura Chávez',
      avatar: 'LC',
      monto: 450.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928108',
      fecha: '03 Abr, 2026',
      concepto: 'Estacionamiento',
      puesto: 'E-001',
      socio: 'Miguel Ángel',
      avatar: 'MA',
      monto: 80.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928109',
      fecha: '03 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'B-001',
      socio: 'Sofía Herrera',
      avatar: 'SH',
      monto: 3600.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928110',
      fecha: '04 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'B-002',
      socio: 'Andrés Gómez',
      avatar: 'AG',
      monto: 175.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928111',
      fecha: '04 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'B-003',
      socio: 'Paula Ríos',
      avatar: 'PR',
      monto: 3400.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928112',
      fecha: '04 Abr, 2026',
      concepto: 'Luz',
      puesto: 'B-004',
      socio: 'Héctor Salas',
      avatar: 'HS',
      monto: 210.3,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928113',
      fecha: '05 Abr, 2026',
      concepto: 'Agua',
      puesto: 'B-005',
      socio: 'Daniela Ponce',
      avatar: 'DP',
      monto: 88.9,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928114',
      fecha: '05 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'B-006',
      socio: 'Raúl Estrada',
      avatar: 'RE',
      monto: 3300.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928115',
      fecha: '05 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'B-007',
      socio: 'Patricia Núñez',
      avatar: 'PN',
      monto: 190.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928116',
      fecha: '05 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'B-008',
      socio: 'Jorge Silva',
      avatar: 'JS',
      monto: 3150.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928117',
      fecha: '06 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'B-009',
      socio: 'Valeria Cruz',
      avatar: 'VC',
      monto: 3550.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928118',
      fecha: '06 Abr, 2026',
      concepto: 'Cuota de Mantenimiento',
      puesto: 'B-010',
      socio: 'Luis Pérez',
      avatar: 'LP',
      monto: 185.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928119',
      fecha: '06 Abr, 2026',
      concepto: 'Estacionamiento',
      puesto: 'E-002',
      socio: 'Claudia Vega',
      avatar: 'CV',
      monto: 85.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928120',
      fecha: '06 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'C-001',
      socio: 'Ricardo Navarro',
      avatar: 'RN',
      monto: 3700.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928121',
      fecha: '07 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'C-002',
      socio: 'Elena Blanco',
      avatar: 'EB',
      monto: 3650.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928122',
      fecha: '07 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'C-003',
      socio: 'Tomás Aguilar',
      avatar: 'TA',
      monto: 170.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928123',
      fecha: '07 Abr, 2026',
      concepto: 'Luz',
      puesto: 'C-004',
      socio: 'Gabriela Castro',
      avatar: 'GC',
      monto: 205.2,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928124',
      fecha: '07 Abr, 2026',
      concepto: 'Agua',
      puesto: 'C-005',
      socio: 'Javier Ortiz',
      avatar: 'JO',
      monto: 92.15,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928125',
      fecha: '08 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'C-006',
      socio: 'Natalia Prieto',
      avatar: 'NP',
      monto: 3450.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928126',
      fecha: '08 Abr, 2026',
      concepto: 'Cuota Extraordinaria',
      puesto: 'C-007',
      socio: 'Sergio León',
      avatar: 'SL',
      monto: 500.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928127',
      fecha: '08 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'C-008',
      socio: 'Carolina Rivas',
      avatar: 'CR',
      monto: 3250.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928128',
      fecha: '08 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'C-009',
      socio: 'Hernán Díaz',
      avatar: 'HD',
      monto: 165.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928129',
      fecha: '09 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'C-010',
      socio: 'Irene Salgado',
      avatar: 'IS',
      monto: 3550.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928130',
      fecha: '09 Abr, 2026',
      concepto: 'Luz',
      puesto: 'D-001',
      socio: 'Pablo Cárdenas',
      avatar: 'PC',
      monto: 215.8,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928131',
      fecha: '09 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'D-002',
      socio: 'Mónica Reyes',
      avatar: 'MR',
      monto: 3400.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928132',
      fecha: '09 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'D-003',
      socio: 'Oscar Valle',
      avatar: 'OV',
      monto: 190.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928133',
      fecha: '10 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'D-004',
      socio: 'Andrea Molina',
      avatar: 'AM',
      monto: 3600.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928134',
      fecha: '10 Abr, 2026',
      concepto: 'Agua',
      puesto: 'D-005',
      socio: 'Felipe Ramos',
      avatar: 'FR',
      monto: 90.4,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928135',
      fecha: '10 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'D-006',
      socio: 'Camila Duarte',
      avatar: 'CD',
      monto: 3300.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928136',
      fecha: '10 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'D-007',
      socio: 'Alberto Lara',
      avatar: 'AL',
      monto: 175.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928137',
      fecha: '11 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'D-008',
      socio: 'Beatriz Quintero',
      avatar: 'BQ',
      monto: 3450.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928138',
      fecha: '11 Abr, 2026',
      concepto: 'Luz',
      puesto: 'D-009',
      socio: 'Gustavo Paredes',
      avatar: 'GP',
      monto: 220.6,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928139',
      fecha: '11 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'D-010',
      socio: 'Verónica Salas',
      avatar: 'VS',
      monto: 3350.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928140',
      fecha: '11 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'E-003',
      socio: 'Hugo Lozano',
      avatar: 'HL',
      monto: 180.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928141',
      fecha: '12 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'E-004',
      socio: 'Rebeca Ortiz',
      avatar: 'RO',
      monto: 3100.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928142',
      fecha: '12 Abr, 2026',
      concepto: 'Cuota de Mantenimiento',
      puesto: 'E-005',
      socio: 'Ignacio Flores',
      avatar: 'IF',
      monto: 195.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928143',
      fecha: '12 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'E-006',
      socio: 'Tamara Ruiz',
      avatar: 'TR',
      monto: 3250.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928144',
      fecha: '12 Abr, 2026',
      concepto: 'Agua',
      puesto: 'E-007',
      socio: 'Marcos Herrera',
      avatar: 'MH',
      monto: 93.2,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928145',
      fecha: '13 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'E-008',
      socio: 'Silvia Fuentes',
      avatar: 'SF',
      monto: 3500.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928146',
      fecha: '13 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'E-009',
      socio: 'Mauricio Vega',
      avatar: 'MV',
      monto: 185.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928147',
      fecha: '13 Abr, 2026',
      concepto: 'Luz',
      puesto: 'E-010',
      socio: 'Julia Campos',
      avatar: 'JC',
      monto: 218.9,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928148',
      fecha: '13 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'F-001',
      socio: 'Rodrigo Peña',
      avatar: 'RP',
      monto: 3400.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928149',
      fecha: '14 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'F-002',
      socio: 'Karen López',
      avatar: 'KL',
      monto: 3350.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928150',
      fecha: '14 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'F-003',
      socio: 'Adrián Roldán',
      avatar: 'AR',
      monto: 190.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928151',
      fecha: '14 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'F-004',
      socio: 'Pilar Cabrera',
      avatar: 'PC',
      monto: 3200.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928152',
      fecha: '14 Abr, 2026',
      concepto: 'Agua',
      puesto: 'F-005',
      socio: 'Esteban Arias',
      avatar: 'EA',
      monto: 91.6,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928153',
      fecha: '15 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'F-006',
      socio: 'Lorena Ibáñez',
      avatar: 'LI',
      monto: 3450.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928154',
      fecha: '15 Abr, 2026',
      concepto: 'Luz',
      puesto: 'F-007',
      socio: 'Santiago Bravo',
      avatar: 'SB',
      monto: 222.4,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928155',
      fecha: '15 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'F-008',
      socio: 'Teresa Méndez',
      avatar: 'TM',
      monto: 3300.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928156',
      fecha: '15 Abr, 2026',
      concepto: 'Mantenimiento',
      puesto: 'F-009',
      socio: 'César Padilla',
      avatar: 'CP',
      monto: 180.0,
      estado: 'Completado',
    },
    {
      idRecibo: '#REC-928157',
      fecha: '16 Abr, 2026',
      concepto: 'Renta Mensual',
      puesto: 'F-010',
      socio: 'Rosa Delgado',
      avatar: 'RD',
      monto: 3500.0,
      estado: 'Completado',
    },
  ]);

  // 1. Recaudación Hoy
  recaudacionHoy = computed(() => {
    const hoy = '14 Abr, 2026'; // new Date()
    return this.allPagos()
      .filter((p) => p.fecha.includes(hoy) && p.estado === 'Completado')
      .reduce((acc, current) => acc + current.monto, 0);
  });

  // 2. Pagos Procesados
  pagosProcesados = computed(() => {
    return this.allPagos().filter((p) => p.estado === 'Completado').length;
  });

  // 3. Total Mes
  totalMes = computed(() => {
    return this.allPagos()
      .filter((p) => p.estado === 'Completado')
      .reduce((acc, current) => acc + current.monto, 0);
  });

  // 4. Deudas Pendientes
  //deudasPendientes = computed(() => {
  //return this.allPagos().filter(p => p.estado === 'Pendiente' || p.estado === 'Vencido').length;
  //});

  pagination = this.paginationService.createPagination(this.allPagos, 10);

  registrarPago() {
    console.log('Abriendo modal de registro...');
  }

  exportarCSV() {
    console.log('Generando reporte...');
  }
}
