import { Component, signal, computed, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Transaccion } from '../../../core/models/transaccion.model';
import { PaginationService } from '../../../core/services/pagination';
import { Pagination } from '../../../shared/components/pagination/pagination';

@Component({
  selector: 'app-pagos',
  standalone: true,
  imports: [CommonModule, Pagination],
  templateUrl: './pagos.html',
  styleUrl: './pagos.css',
})
export class Pagos {
  private paginationService = inject(PaginationService);
  // datos (simulando lo que vendrá del backend)
  allTransactions = signal<Transaccion[]>([
    {
      fecha: '24 oct. 2023',
      hora: '09:42 AM',
      puestoId: 'B-102',
      inquilino: 'The Coffee Hub Ltd.',
      concepto: 'Renta Mensual',
      monto: 2450.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992381',
    },
    {
      fecha: '23 oct. 2023',
      hora: '02:15 PM',
      puestoId: 'A-045',
      inquilino: 'Urban Greens Co.',
      concepto: 'Mantenimiento',
      monto: 120.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992380',
    },
    {
      fecha: '25 oct. 2023',
      hora: '10:05 AM',
      puestoId: 'C-210',
      inquilino: 'Fresh Bites S.A.',
      concepto: 'Renta Mensual',
      monto: 1980.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992382',
    },
    {
      fecha: '25 oct. 2023',
      hora: '11:32 AM',
      puestoId: 'D-011',
      inquilino: 'Tech Corner MX',
      concepto: 'Luz',
      monto: 340.5,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992383',
    },
    {
      fecha: '26 oct. 2023',
      hora: '09:10 AM',
      puestoId: 'B-078',
      inquilino: 'Panadería La Espiga',
      concepto: 'Renta Mensual',
      monto: 1730.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992384',
    },
    {
      fecha: '26 oct. 2023',
      hora: '04:47 PM',
      puestoId: 'A-030',
      inquilino: 'Mercadito Orgánico',
      concepto: 'Agua',
      monto: 95.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992385',
    },
    {
      fecha: '27 oct. 2023',
      hora: '08:55 AM',
      puestoId: 'C-099',
      inquilino: 'Fashion Point',
      concepto: 'Renta Mensual',
      monto: 2200.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992386',
    },
    {
      fecha: '27 oct. 2023',
      hora: '01:22 PM',
      puestoId: 'D-034',
      inquilino: 'Healthy Corner',
      concepto: 'Mantenimiento',
      monto: 135.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992387',
    },
    {
      fecha: '28 oct. 2023',
      hora: '09:05 AM',
      puestoId: 'B-020',
      inquilino: 'La Esquina del Café',
      concepto: 'Renta Mensual',
      monto: 2100.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992388',
    },
    {
      fecha: '28 oct. 2023',
      hora: '05:18 PM',
      puestoId: 'A-067',
      inquilino: 'Urban Greens Co.',
      concepto: 'Luz',
      monto: 180.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992389',
    },
    {
      fecha: '29 oct. 2023',
      hora: '10:41 AM',
      puestoId: 'C-150',
      inquilino: 'The Coffee Hub Ltd.',
      concepto: 'Mantenimiento',
      monto: 160.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992390',
    },
    {
      fecha: '29 oct. 2023',
      hora: '03:05 PM',
      puestoId: 'D-020',
      inquilino: 'Tech Corner MX',
      concepto: 'Agua',
      monto: 88.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992391',
    },
    {
      fecha: '30 oct. 2023',
      hora: '09:13 AM',
      puestoId: 'B-111',
      inquilino: 'Urban Greens Co.',
      concepto: 'Renta Mensual',
      monto: 2300.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992392',
    },
    {
      fecha: '30 oct. 2023',
      hora: '11:56 AM',
      puestoId: 'A-010',
      inquilino: 'Mercadito Orgánico',
      concepto: 'Mantenimiento',
      monto: 130.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992393',
    },
    {
      fecha: '31 oct. 2023',
      hora: '08:37 AM',
      puestoId: 'C-005',
      inquilino: 'Panadería La Espiga',
      concepto: 'Renta Mensual',
      monto: 1650.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992394',
    },
    {
      fecha: '31 oct. 2023',
      hora: '06:21 PM',
      puestoId: 'D-099',
      inquilino: 'Fashion Point',
      concepto: 'Luz',
      monto: 210.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992395',
    },
    {
      fecha: '01 nov. 2023',
      hora: '09:00 AM',
      puestoId: 'B-054',
      inquilino: 'Healthy Corner',
      concepto: 'Renta Mensual',
      monto: 1890.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992396',
    },
    {
      fecha: '01 nov. 2023',
      hora: '03:44 PM',
      puestoId: 'A-088',
      inquilino: 'La Esquina del Café',
      concepto: 'Agua',
      monto: 102.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992397',
    },
    {
      fecha: '02 nov. 2023',
      hora: '10:19 AM',
      puestoId: 'C-207',
      inquilino: 'The Coffee Hub Ltd.',
      concepto: 'Renta Mensual',
      monto: 2500.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992398',
    },
    {
      fecha: '02 nov. 2023',
      hora: '12:33 PM',
      puestoId: 'D-040',
      inquilino: 'Urban Greens Co.',
      concepto: 'Mantenimiento',
      monto: 145.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992399',
    },
    {
      fecha: '03 nov. 2023',
      hora: '09:08 AM',
      puestoId: 'B-200',
      inquilino: 'Tech Corner MX',
      concepto: 'Renta Mensual',
      monto: 2600.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992400',
    },
    {
      fecha: '03 nov. 2023',
      hora: '04:02 PM',
      puestoId: 'A-025',
      inquilino: 'Panadería La Espiga',
      concepto: 'Agua',
      monto: 94.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992401',
    },
    {
      fecha: '04 nov. 2023',
      hora: '11:21 AM',
      puestoId: 'C-080',
      inquilino: 'Fashion Point',
      concepto: 'Renta Mensual',
      monto: 2150.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992402',
    },
    {
      fecha: '04 nov. 2023',
      hora: '02:55 PM',
      puestoId: 'D-060',
      inquilino: 'Healthy Corner',
      concepto: 'Luz',
      monto: 176.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992403',
    },
    {
      fecha: '05 nov. 2023',
      hora: '09:31 AM',
      puestoId: 'B-015',
      inquilino: 'La Esquina del Café',
      concepto: 'Renta Mensual',
      monto: 2050.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992404',
    },
    {
      fecha: '05 nov. 2023',
      hora: '05:19 PM',
      puestoId: 'A-050',
      inquilino: 'Mercadito Orgánico',
      concepto: 'Mantenimiento',
      monto: 125.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992405',
    },
    {
      fecha: '06 nov. 2023',
      hora: '10:48 AM',
      puestoId: 'C-130',
      inquilino: 'Fresh Bites S.A.',
      concepto: 'Renta Mensual',
      monto: 1920.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992406',
    },
    {
      fecha: '06 nov. 2023',
      hora: '01:36 PM',
      puestoId: 'D-101',
      inquilino: 'Urban Greens Co.',
      concepto: 'Agua',
      monto: 99.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992407',
    },
    {
      fecha: '07 nov. 2023',
      hora: '08:59 AM',
      puestoId: 'B-060',
      inquilino: 'The Coffee Hub Ltd.',
      concepto: 'Renta Mensual',
      monto: 2480.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992408',
    },
    {
      fecha: '07 nov. 2023',
      hora: '03:11 PM',
      puestoId: 'A-075',
      inquilino: 'Panadería La Espiga',
      concepto: 'Luz',
      monto: 167.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992409',
    },
    {
      fecha: '08 nov. 2023',
      hora: '09:25 AM',
      puestoId: 'C-012',
      inquilino: 'Healthy Corner',
      concepto: 'Renta Mensual',
      monto: 1810.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992410',
    },
    {
      fecha: '08 nov. 2023',
      hora: '04:45 PM',
      puestoId: 'D-025',
      inquilino: 'Fashion Point',
      concepto: 'Mantenimiento',
      monto: 140.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992411',
    },
    {
      fecha: '09 nov. 2023',
      hora: '10:12 AM',
      puestoId: 'B-089',
      inquilino: 'Mercadito Orgánico',
      concepto: 'Renta Mensual',
      monto: 1880.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992412',
    },
    {
      fecha: '09 nov. 2023',
      hora: '02:50 PM',
      puestoId: 'A-005',
      inquilino: 'La Esquina del Café',
      concepto: 'Agua',
      monto: 97.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992413',
    },
    {
      fecha: '10 nov. 2023',
      hora: '09:03 AM',
      puestoId: 'C-045',
      inquilino: 'Urban Greens Co.',
      concepto: 'Renta Mensual',
      monto: 2250.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992414',
    },
    {
      fecha: '10 nov. 2023',
      hora: '06:07 PM',
      puestoId: 'D-077',
      inquilino: 'The Coffee Hub Ltd.',
      concepto: 'Luz',
      monto: 190.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992415',
    },
    {
      fecha: '11 nov. 2023',
      hora: '08:47 AM',
      puestoId: 'B-140',
      inquilino: 'Tech Corner MX',
      concepto: 'Renta Mensual',
      monto: 2700.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992416',
    },
    {
      fecha: '11 nov. 2023',
      hora: '12:29 PM',
      puestoId: 'A-090',
      inquilino: 'Fresh Bites S.A.',
      concepto: 'Mantenimiento',
      monto: 155.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992417',
    },
    {
      fecha: '12 nov. 2023',
      hora: '10:34 AM',
      puestoId: 'C-060',
      inquilino: 'Panadería La Espiga',
      concepto: 'Renta Mensual',
      monto: 1705.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992418',
    },
    {
      fecha: '12 nov. 2023',
      hora: '02:40 PM',
      puestoId: 'D-010',
      inquilino: 'Healthy Corner',
      concepto: 'Agua',
      monto: 92.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992419',
    },
    {
      fecha: '13 nov. 2023',
      hora: '09:19 AM',
      puestoId: 'B-030',
      inquilino: 'Fashion Point',
      concepto: 'Renta Mensual',
      monto: 2180.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992420',
    },
    {
      fecha: '13 nov. 2023',
      hora: '05:33 PM',
      puestoId: 'A-020',
      inquilino: 'Urban Greens Co.',
      concepto: 'Luz',
      monto: 185.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992421',
    },
    {
      fecha: '14 nov. 2023',
      hora: '10:07 AM',
      puestoId: 'C-110',
      inquilino: 'La Esquina del Café',
      concepto: 'Mantenimiento',
      monto: 138.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992422',
    },
    {
      fecha: '14 nov. 2023',
      hora: '01:49 PM',
      puestoId: 'D-050',
      inquilino: 'Mercadito Orgánico',
      concepto: 'Agua',
      monto: 101.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992423',
    },
    {
      fecha: '15 nov. 2023',
      hora: '09:02 AM',
      puestoId: 'B-077',
      inquilino: 'The Coffee Hub Ltd.',
      concepto: 'Renta Mensual',
      monto: 2525.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992424',
    },
    {
      fecha: '15 nov. 2023',
      hora: '03:27 PM',
      puestoId: 'A-035',
      inquilino: 'Tech Corner MX',
      concepto: 'Mantenimiento',
      monto: 150.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992425',
    },
    {
      fecha: '16 nov. 2023',
      hora: '08:58 AM',
      puestoId: 'C-020',
      inquilino: 'Healthy Corner',
      concepto: 'Renta Mensual',
      monto: 1830.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992426',
    },
    {
      fecha: '16 nov. 2023',
      hora: '05:05 PM',
      puestoId: 'D-070',
      inquilino: 'Panadería La Espiga',
      concepto: 'Luz',
      monto: 172.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992427',
    },
    {
      fecha: '17 nov. 2023',
      hora: '09:44 AM',
      puestoId: 'B-010',
      inquilino: 'Fashion Point',
      concepto: 'Renta Mensual',
      monto: 2220.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992428',
    },
    {
      fecha: '17 nov. 2023',
      hora: '02:38 PM',
      puestoId: 'A-055',
      inquilino: 'Fresh Bites S.A.',
      concepto: 'Agua',
      monto: 98.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992429',
    },
    {
      fecha: '18 nov. 2023',
      hora: '10:11 AM',
      puestoId: 'C-095',
      inquilino: 'Urban Greens Co.',
      concepto: 'Renta Mensual',
      monto: 2320.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992430',
    },
    {
      fecha: '18 nov. 2023',
      hora: '04:29 PM',
      puestoId: 'D-015',
      inquilino: 'La Esquina del Café',
      concepto: 'Mantenimiento',
      monto: 142.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992431',
    },
    {
      fecha: '19 nov. 2023',
      hora: '09:28 AM',
      puestoId: 'B-025',
      inquilino: 'Mercadito Orgánico',
      concepto: 'Renta Mensual',
      monto: 1910.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992432',
    },
    {
      fecha: '19 nov. 2023',
      hora: '01:57 PM',
      puestoId: 'A-042',
      inquilino: 'The Coffee Hub Ltd.',
      concepto: 'Luz',
      monto: 195.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992433',
    },
    {
      fecha: '20 nov. 2023',
      hora: '10:22 AM',
      puestoId: 'C-140',
      inquilino: 'Tech Corner MX',
      concepto: 'Renta Mensual',
      monto: 2750.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992434',
    },
    {
      fecha: '20 nov. 2023',
      hora: '03:41 PM',
      puestoId: 'D-030',
      inquilino: 'Healthy Corner',
      concepto: 'Mantenimiento',
      monto: 148.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992435',
    },
    {
      fecha: '21 nov. 2023',
      hora: '08:50 AM',
      puestoId: 'B-099',
      inquilino: 'Panadería La Espiga',
      concepto: 'Renta Mensual',
      monto: 1760.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992436',
    },
    {
      fecha: '21 nov. 2023',
      hora: '05:02 PM',
      puestoId: 'A-060',
      inquilino: 'Fashion Point',
      concepto: 'Agua',
      monto: 103.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992437',
    },
    {
      fecha: '22 nov. 2023',
      hora: '09:36 AM',
      puestoId: 'C-025',
      inquilino: 'Urban Greens Co.',
      concepto: 'Mantenimiento',
      monto: 137.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992438',
    },
    {
      fecha: '22 nov. 2023',
      hora: '02:25 PM',
      puestoId: 'D-085',
      inquilino: 'Mercadito Orgánico',
      concepto: 'Luz',
      monto: 178.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992439',
    },
    {
      fecha: '23 nov. 2023',
      hora: '09:04 AM',
      puestoId: 'B-070',
      inquilino: 'La Esquina del Café',
      concepto: 'Renta Mensual',
      monto: 2080.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992440',
    },
    {
      fecha: '23 nov. 2023',
      hora: '04:11 PM',
      puestoId: 'A-015',
      inquilino: 'Healthy Corner',
      concepto: 'Agua',
      monto: 100.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992441',
    },
    {
      fecha: '24 nov. 2023',
      hora: '10:18 AM',
      puestoId: 'C-180',
      inquilino: 'Fresh Bites S.A.',
      concepto: 'Renta Mensual',
      monto: 1950.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992442',
    },
    {
      fecha: '24 nov. 2023',
      hora: '01:46 PM',
      puestoId: 'D-055',
      inquilino: 'Tech Corner MX',
      concepto: 'Mantenimiento',
      monto: 152.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992443',
    },
    {
      fecha: '25 nov. 2023',
      hora: '09:42 AM',
      puestoId: 'B-033',
      inquilino: 'The Coffee Hub Ltd.',
      concepto: 'Renta Mensual',
      monto: 2490.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992444',
    },
    {
      fecha: '25 nov. 2023',
      hora: '03:59 PM',
      puestoId: 'A-048',
      inquilino: 'Fashion Point',
      concepto: 'Luz',
      monto: 188.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992445',
    },
    {
      fecha: '26 nov. 2023',
      hora: '08:53 AM',
      puestoId: 'C-070',
      inquilino: 'Panadería La Espiga',
      concepto: 'Renta Mensual',
      monto: 1745.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992446',
    },
    {
      fecha: '26 nov. 2023',
      hora: '02:33 PM',
      puestoId: 'D-095',
      inquilino: 'Urban Greens Co.',
      concepto: 'Agua',
      monto: 96.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992447',
    },
    {
      fecha: '27 nov. 2023',
      hora: '09:29 AM',
      puestoId: 'B-022',
      inquilino: 'Mercadito Orgánico',
      concepto: 'Renta Mensual',
      monto: 1930.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992448',
    },
    {
      fecha: '27 nov. 2023',
      hora: '05:27 PM',
      puestoId: 'A-082',
      inquilino: 'La Esquina del Café',
      concepto: 'Mantenimiento',
      monto: 129.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992449',
    },
    {
      fecha: '28 nov. 2023',
      hora: '10:06 AM',
      puestoId: 'C-040',
      inquilino: 'Healthy Corner',
      concepto: 'Renta Mensual',
      monto: 1865.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992450',
    },
    {
      fecha: '28 nov. 2023',
      hora: '01:54 PM',
      puestoId: 'D-045',
      inquilino: 'Fresh Bites S.A.',
      concepto: 'Agua',
      monto: 105.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992451',
    },
    {
      fecha: '29 nov. 2023',
      hora: '09:11 AM',
      puestoId: 'B-066',
      inquilino: 'The Coffee Hub Ltd.',
      concepto: 'Renta Mensual',
      monto: 2510.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992452',
    },
    {
      fecha: '29 nov. 2023',
      hora: '03:03 PM',
      puestoId: 'A-012',
      inquilino: 'Tech Corner MX',
      concepto: 'Mantenimiento',
      monto: 153.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992453',
    },
    {
      fecha: '30 nov. 2023',
      hora: '08:57 AM',
      puestoId: 'C-160',
      inquilino: 'Urban Greens Co.',
      concepto: 'Renta Mensual',
      monto: 2350.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992454',
    },
    {
      fecha: '30 nov. 2023',
      hora: '04:36 PM',
      puestoId: 'D-005',
      inquilino: 'Panadería La Espiga',
      concepto: 'Luz',
      monto: 181.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992455',
    },
    {
      fecha: '01 dic. 2023',
      hora: '09:23 AM',
      puestoId: 'B-018',
      inquilino: 'Fashion Point',
      concepto: 'Renta Mensual',
      monto: 2240.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992456',
    },
    {
      fecha: '01 dic. 2023',
      hora: '02:44 PM',
      puestoId: 'A-065',
      inquilino: 'Mercadito Orgánico',
      concepto: 'Agua',
      monto: 99.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992457',
    },
    {
      fecha: '02 dic. 2023',
      hora: '10:15 AM',
      puestoId: 'C-055',
      inquilino: 'La Esquina del Café',
      concepto: 'Mantenimiento',
      monto: 134.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992458',
    },
    {
      fecha: '02 dic. 2023',
      hora: '06:05 PM',
      puestoId: 'D-065',
      inquilino: 'Healthy Corner',
      concepto: 'Luz',
      monto: 179.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992459',
    },
    {
      fecha: '03 dic. 2023',
      hora: '08:49 AM',
      puestoId: 'B-044',
      inquilino: 'Fresh Bites S.A.',
      concepto: 'Renta Mensual',
      monto: 1975.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992460',
    },
    {
      fecha: '03 dic. 2023',
      hora: '01:39 PM',
      puestoId: 'A-038',
      inquilino: 'Tech Corner MX',
      concepto: 'Agua',
      monto: 101.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992461',
    },
    {
      fecha: '04 dic. 2023',
      hora: '09:06 AM',
      puestoId: 'C-100',
      inquilino: 'The Coffee Hub Ltd.',
      concepto: 'Renta Mensual',
      monto: 2530.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992462',
    },
    {
      fecha: '04 dic. 2023',
      hora: '03:22 PM',
      puestoId: 'D-025',
      inquilino: 'Urban Greens Co.',
      concepto: 'Mantenimiento',
      monto: 149.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992463',
    },
    {
      fecha: '05 dic. 2023',
      hora: '09:47 AM',
      puestoId: 'B-090',
      inquilino: 'Panadería La Espiga',
      concepto: 'Renta Mensual',
      monto: 1790.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992464',
    },
    {
      fecha: '05 dic. 2023',
      hora: '05:18 PM',
      puestoId: 'A-027',
      inquilino: 'Fashion Point',
      concepto: 'Luz',
      monto: 187.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992465',
    },
    {
      fecha: '06 dic. 2023',
      hora: '10:28 AM',
      puestoId: 'C-030',
      inquilino: 'Mercadito Orgánico',
      concepto: 'Renta Mensual',
      monto: 1960.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992466',
    },
    {
      fecha: '06 dic. 2023',
      hora: '02:59 PM',
      puestoId: 'D-090',
      inquilino: 'La Esquina del Café',
      concepto: 'Agua',
      monto: 104.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992467',
    },
    {
      fecha: '07 dic. 2023',
      hora: '09:14 AM',
      puestoId: 'B-011',
      inquilino: 'Healthy Corner',
      concepto: 'Renta Mensual',
      monto: 1885.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992468',
    },
    {
      fecha: '07 dic. 2023',
      hora: '04:48 PM',
      puestoId: 'A-073',
      inquilino: 'Fresh Bites S.A.',
      concepto: 'Mantenimiento',
      monto: 141.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992469',
    },
    {
      fecha: '08 dic. 2023',
      hora: '08:52 AM',
      puestoId: 'C-075',
      inquilino: 'Tech Corner MX',
      concepto: 'Renta Mensual',
      monto: 2800.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992470',
    },
    {
      fecha: '08 dic. 2023',
      hora: '01:32 PM',
      puestoId: 'D-048',
      inquilino: 'The Coffee Hub Ltd.',
      concepto: 'Agua',
      monto: 107.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992471',
    },
    {
      fecha: '09 dic. 2023',
      hora: '09:39 AM',
      puestoId: 'B-052',
      inquilino: 'Urban Greens Co.',
      concepto: 'Renta Mensual',
      monto: 2380.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992472',
    },
    {
      fecha: '09 dic. 2023',
      hora: '03:09 PM',
      puestoId: 'A-017',
      inquilino: 'Panadería La Espiga',
      concepto: 'Mantenimiento',
      monto: 133.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992473',
    },
    {
      fecha: '10 dic. 2023',
      hora: '10:01 AM',
      puestoId: 'C-090',
      inquilino: 'Fashion Point',
      concepto: 'Renta Mensual',
      monto: 2275.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992474',
    },
    {
      fecha: '10 dic. 2023',
      hora: '06:12 PM',
      puestoId: 'D-020',
      inquilino: 'Mercadito Orgánico',
      concepto: 'Luz',
      monto: 183.0,
      metodoPago: 'Efectivo',
      idRecibo: '#MP-992475',
    },
    {
      fecha: '11 dic. 2023',
      hora: '09:07 AM',
      puestoId: 'B-039',
      inquilino: 'La Esquina del Café',
      concepto: 'Renta Mensual',
      monto: 2110.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992476',
    },
    {
      fecha: '11 dic. 2023',
      hora: '02:21 PM',
      puestoId: 'A-033',
      inquilino: 'Healthy Corner',
      concepto: 'Agua',
      monto: 102.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992477',
    },
    {
      fecha: '12 dic. 2023',
      hora: '10:26 AM',
      puestoId: 'C-010',
      inquilino: 'Fresh Bites S.A.',
      concepto: 'Renta Mensual',
      monto: 1995.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992478',
    },
    {
      fecha: '12 dic. 2023',
      hora: '05:34 PM',
      puestoId: 'D-035',
      inquilino: 'Tech Corner MX',
      concepto: 'Mantenimiento',
      monto: 157.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992479',
    },
    {
      fecha: '11 dic. 2023',
      hora: '09:07 AM',
      puestoId: 'B-039',
      inquilino: 'La Esquina del Café',
      concepto: 'Renta Mensual',
      monto: 2110.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992476',
    },
    {
      fecha: '11 dic. 2023',
      hora: '02:21 PM',
      puestoId: 'A-033',
      inquilino: 'Healthy Corner',
      concepto: 'Agua',
      monto: 102.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992477',
    },
    {
      fecha: '12 dic. 2023',
      hora: '10:26 AM',
      puestoId: 'C-010',
      inquilino: 'Fresh Bites S.A.',
      concepto: 'Renta Mensual',
      monto: 1995.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992478',
    },
    {
      fecha: '12 dic. 2023',
      hora: '05:34 PM',
      puestoId: 'D-035',
      inquilino: 'Tech Corner MX',
      concepto: 'Mantenimiento',
      monto: 157.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992479',
    },
    {
      fecha: '11 dic. 2023',
      hora: '09:07 AM',
      puestoId: 'B-039',
      inquilino: 'La Esquina del Café',
      concepto: 'Renta Mensual',
      monto: 2110.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992476',
    },
    {
      fecha: '11 dic. 2023',
      hora: '02:21 PM',
      puestoId: 'A-033',
      inquilino: 'Healthy Corner',
      concepto: 'Agua',
      monto: 102.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992477',
    },
    {
      fecha: '12 dic. 2023',
      hora: '10:26 AM',
      puestoId: 'C-010',
      inquilino: 'Fresh Bites S.A.',
      concepto: 'Renta Mensual',
      monto: 1995.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992478',
    },
    {
      fecha: '12 dic. 2023',
      hora: '05:34 PM',
      puestoId: 'D-035',
      inquilino: 'Tech Corner MX',
      concepto: 'Mantenimiento',
      monto: 157.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992479',
    },
    {
      fecha: '11 dic. 2023',
      hora: '09:07 AM',
      puestoId: 'B-039',
      inquilino: 'La Esquina del Café',
      concepto: 'Renta Mensual',
      monto: 2110.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992476',
    },
    {
      fecha: '11 dic. 2023',
      hora: '02:21 PM',
      puestoId: 'A-033',
      inquilino: 'Healthy Corner',
      concepto: 'Agua',
      monto: 102.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992477',
    },
    {
      fecha: '12 dic. 2023',
      hora: '10:26 AM',
      puestoId: 'C-010',
      inquilino: 'Fresh Bites S.A.',
      concepto: 'Renta Mensual',
      monto: 1995.0,
      metodoPago: 'Transferencia',
      idRecibo: '#MP-992478',
    },
    {
      fecha: '12 dic. 2023',
      hora: '05:34 PM',
      puestoId: 'D-035',
      inquilino: 'Tech Corner MX',
      concepto: 'Mantenimiento',
      monto: 157.0,
      metodoPago: 'Tarjeta',
      idRecibo: '#MP-992479',
    },
  ]);

  pagination = this.paginationService.createPagination(this.allTransactions, 15);

  /*
    ngOnInit() {
      this.miServicio.getTransacciones().subscribe((datos) => {
        this.allTransactions.set(datos);
      });
    }
  */
}
